package tk.ungarscool1.bot.telemetry.entities;

public enum Permissions {
	AVERAGE_CONNECTED_TIME, AVERAGE_LISTEN_TIME, AVERAGE_PLAY_TIME, FAVORITE_GAME, FAVORITE_CHANNEL, FAVORITE_MUSIC, FAVORITE_MUSIC_ARTIST, FAVORITE_MUSIC_ALBUM, NUMBER_OF_MESSAGE, TYPING_TIME;
}
